name: Integration

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build-api:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - run: |
          cd ./api
          ls
