name: Integration

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build-api:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: cd ./api && ls
